version: '3'

networks:
  spring:
    driver: bridge

services:
  db:
    image: postgres
    networks:
      - spring
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data